# Data Library Get History Synchronous Performance (30 RICs)

Importing requires libraries

In [2]:
import os
import time
from IPython.display import Markdown, display
import lseg.data as ld
from lseg.data import session
from lseg.data._errors import LDError
from dotenv import load_dotenv

Loading Platform session (Data Platform) credential from `.env` file.

In [3]:
# Load environment variables from .env file
load_dotenv(dotenv_path='.env')
# Retrieve Platform Session credentials from environment variables
app_key = os.getenv('LSEG_API_KEY')
username = os.getenv('LSEG_MACHINE_ID')
password = os.getenv('LSEG_PASSWORD')

Define required variables.

In [4]:
# -- Top 30 S&P 500 companies ----------------------------------------------------
INSTRUMENTS = [
"NVDA.O",
"AAPL.O",
"MSFT.O",
"AMZN.O",
"GOOG.O",
"AVGO.O",
"META.O",
"ORCL.N",
"IBM.N",
"PLTR.O",
"NFLX.O",
"TSLA.O",
"CRM.N",
"AMD.O",
"INTC.O",
"ARM.O",
"TXN.O",
"CSCO.O",
"WMT.O",
"LLY.N",
"JPM.N",
"XOM.N",
"V.N",
"JNJ.N",
"MU.O",
"MA.N",
"COST.O",
"CVX.N",
"BAC.N",
"CAT.N",
]

# ── Date range ─────────────────────────────────────────────────────────────────
START = "2025-11-01T00:00:00Z"
END   = "2026-02-28T23:59:59Z"

# ── Event correction filters ───────────────────────────────────────────────────
EVENT_ADJUSTMENTS = ["exchangeCorrection",
                    "manualCorrection",
                    "CCH",
                    "CRE",
                    "RPO",
                    "RTS"]

# ── Field lists ─────────────────────────────────────────────────────────────────
INTERDAY_FIELDS = ["BID", "ASK", "OPEN_PRC", "HIGH_1", "LOW_1", "TRDPRC_1", "NUM_MOVES", "TRNOVR_UNS"]

Initialize and open the session.

In [5]:
# Create a platform session with provided credentials for authentication
ld_session = session.platform.Definition(
         app_key=app_key,
         grant=session.platform.GrantPassword(
             username=username,
             password=password
         ),
         signon_control=True
).get_session()

# Set this session as the default for all subsequent Data Library calls
session.set_default(ld_session)

# Open the connection to the LSEG Data Platform
ld_session.open()

Requests 30 Instruments (single-RIC looping) synchronously with time counter.

In [6]:
hist_data = []
display(Markdown("**Start the wall-clock timer...**"))
start_time = time.perf_counter()
try:
    for instrument in INSTRUMENTS:
        # Fetch historical pricing data for the instrument
        data = ld.get_history(
            universe=instrument,
            start=START,
            end=END,
            adjustments=EVENT_ADJUSTMENTS,
            fields=INTERDAY_FIELDS,
            interval="1D"
        )
        hist_data.append(data)
        time.sleep(.05)  # Sleep for 0.05 seconds to avoid hitting rate limits
        
except LDError as e:
    print(f"**Exception:** {e}")
finally:
    elapsed = time.perf_counter() - start_time
    elapsed_string = f"**Sending Historical-Pricing Interday Historical Summaries (Daily) for ({len(INSTRUMENTS)}) RICs in {elapsed:0.2f} seconds.**"
    display(Markdown(elapsed_string))

**Start the wall-clock timer...**

**Sending Historical-Pricing Interday Historical Summaries (Daily) for (30) RICs in 48.95 seconds.**

Display Data in DF

In [7]:
for df in hist_data:
    display(df)

NVDA.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,207.0,207.03,208.08,211.335,205.56,206.88,3054457,37549986769
2025-11-04,198.7,198.71,203.0,203.9699,197.93,198.69,3565682,37901976083
2025-11-05,195.15,195.16,198.77,202.92,194.65,195.21,2775987,34120584820
2025-11-06,188.16,188.19,196.42,197.62,186.38,188.08,3884236,42465767945
2025-11-07,188.24,188.26,184.9,188.32,178.91,188.15,4573319,48737152026
...,...,...,...,...,...,...,...,...
2026-02-23,191.63,191.66,191.4,193.95,189.575,191.55,2548773,32831754707
2026-02-24,192.84,192.86,191.49,193.77,187.4,192.85,2330529,33633192693
2026-02-25,195.69,195.88,194.45,197.6299,193.79,195.56,3175611,49300579284
2026-02-26,184.87,184.89,194.27,194.29,184.315,184.89,4877577,67579404866
2026-02-27,177.14,177.15,181.25,182.59,176.38,177.19,3823737,55882286062

AAPL.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,269.04,269.06,270.42,270.85,266.25,269.05,731851,13467187915
2025-11-04,270.03,270.21,268.325,271.486,267.615,270.04,713303,13291815937
2025-11-05,270.06,270.12,268.61,271.7,266.93,270.14,588621,11786398543
2025-11-06,269.64,269.8,267.89,273.4,267.89,269.77,718679,13861638554
2025-11-07,268.46,268.58,269.795,272.29,266.77,268.47,754451,12973407220
...,...,...,...,...,...,...,...,...
2026-02-23,266.38,266.42,263.49,269.43,263.381,266.18,667289,9945411905
2026-02-24,272.16,272.19,267.86,274.89,267.71,272.14,651152,12812785381
2026-02-25,274.14,274.2,271.78,274.94,271.05,274.23,584207,9229781428
2026-02-26,272.99,273.01,274.945,276.11,270.795,272.95,607281,8846778363
2026-02-27,264.17,264.21,272.81,272.81,262.89,264.18,768081,19221957495

MSFT.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,516.98,517.12,519.805,524.96,514.59,517.03,684446,11602236303
2025-11-04,514.75,514.82,511.76,515.55,507.84,514.33,611336,10755292655
2025-11-05,506.9,506.99,513.3,514.83,506.575,507.16,655631,11719403377
2025-11-06,497.16,497.39,505.66,505.7,495.81,497.1,835591,13665182315
2025-11-07,496.83,496.94,496.945,499.377,493.25,496.82,676492,11916037399
...,...,...,...,...,...,...,...,...
2026-02-23,384.45,384.61,395.0,395.36,383.1,384.47,1166464,16723590827
2026-02-24,388.96,389.01,384.14,389.36,381.71,389.0,743750,13123772887
2026-02-25,400.49,400.5,390.525,401.47,390.16,400.6,917541,17358629960
2026-02-26,401.77,401.81,404.71,407.49,398.74,401.72,777464,13827085235
2026-02-27,392.72,392.75,390.88,396.82,389.88,392.74,881208,20206339261

AMZN.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,254.04,254.07,255.36,258.6,252.9,254.0,1284947,24519644359
2025-11-04,249.38,249.47,250.38,257.01,248.66,249.32,777708,12936426003
2025-11-05,250.24,250.25,249.03,251.0,246.16,250.2,598484,10122651523
2025-11-06,243.07,243.11,249.155,250.38,242.17,243.04,697594,11262940033
2025-11-07,244.4,244.43,242.9,244.9,238.49,244.41,667465,11215590548
...,...,...,...,...,...,...,...,...
2026-02-23,205.26,205.3,208.095,208.43,203.11,205.27,796501,10978998094
2026-02-24,208.55,208.58,205.47,210.36,203.25,208.56,594489,8559704894
2026-02-25,210.65,210.69,210.46,211.59,208.93,210.64,552150,8689520871
2026-02-26,207.9,207.92,210.73,211.05,205.345,207.92,687335,9927434080
2026-02-27,209.99,210.01,206.83,210.33,205.2,210.0,659180,11986745553

GOOG.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,284.19,284.26,282.42,285.94,280.3701,284.12,348118,5575614641
2025-11-04,278.01,278.06,277.065,281.8336,276.865,278.06,340940,5051090572
2025-11-05,284.73,284.78,279.38,286.7,277.88,284.75,358572,5693479977
2025-11-06,285.33,285.39,285.735,288.81,281.62,285.34,418790,6596078754
2025-11-07,279.67,279.7,284.21,284.5,275.74,279.7,408751,6136236221
...,...,...,...,...,...,...,...,...
2026-02-23,311.68,311.73,319.14,319.455,309.99,311.69,372547,5537258582
2026-02-24,310.91,310.98,310.64,312.37,306.09,310.92,289526,4665013512
2026-02-25,313.01,313.05,312.12,313.66,309.36,313.03,360299,6299636717
2026-02-26,307.16,307.22,312.805,313.0,302.41,307.15,436957,6859346344
2026-02-27,311.23,311.32,303.94,312.08,303.5905,311.43,361082,10341519353

AVGO.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,362.51,362.63,372.0,374.85,361.98,362.55,402404,6270045875
2025-11-04,351.92,352.38,358.52,368.95,351.0,351.94,518186,8585958816
2025-11-05,358.8,358.83,350.89,364.8699,350.0913,358.98,421943,6157527382
2025-11-06,355.68,355.77,360.11,363.5,352.71,355.59,421367,7099913320
2025-11-07,349.43,349.47,354.185,354.5,337.27,349.43,538161,7567335218
...,...,...,...,...,...,...,...,...
2026-02-23,330.3,330.43,332.25,338.5,325.32,330.34,316941,5455761685
2026-02-24,325.4,325.5,322.54,328.305,314.45,325.49,393326,7658494383
2026-02-25,332.3,332.31,330.74,335.91,329.28,332.31,365797,6711407101
2026-02-26,321.66,321.71,326.5,326.575,307.93,321.7,666954,10456477754
2026-02-27,319.53,319.62,310.7,320.0,310.0,319.55,372424,8913467807

META.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,637.79,638.0,656.0,659.3299,636.18,637.71,1138020,21355480424
2025-11-04,627.4,627.6,628.035,641.7399,626.01,627.32,934014,17265707423
2025-11-05,636.0,636.18,632.31,642.23,626.5375,635.95,650301,12845791469
2025-11-06,619.07,619.12,635.85,636.0,618.0,618.94,795339,14720241326
2025-11-07,621.54,621.71,616.485,622.1348,601.2,621.71,954856,18325054804
...,...,...,...,...,...,...,...,...
2026-02-23,637.3,637.47,652.54,657.7,636.0,637.25,295137,5531648940
2026-02-24,639.03,639.05,633.08,641.11,628.98,639.3,282593,6459649571
2026-02-25,653.69,653.82,642.53,653.88,642.14,653.69,294391,7376393830
2026-02-26,656.82,657.05,650.55,661.0,647.5,657.01,280797,6973110115
2026-02-27,647.84,648.2,643.45,649.44,638.12,648.18,328929,10137240298

ORCL.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,257.84,257.85,264.84,264.84,255.24,257.85,42220,830384092
2025-11-04,248.14,248.15,252.0,255.28,245.22,248.17,52392,924875465
2025-11-05,250.33,250.4,248.09,252.4,247.08,250.31,31088,625145758
2025-11-06,243.83,243.87,247.5,248.31,239.4,243.8,49348,748447681
2025-11-07,239.24,239.27,239.4,239.42,232.36,239.26,70665,958925947
...,...,...,...,...,...,...,...,...
2026-02-23,141.27,141.3,144.09,144.24,138.59,141.31,72959,744923055
2026-02-24,146.1,146.14,140.6,146.76,138.77,146.14,33597,514450807
2026-02-25,147.87,147.89,149.54,153.26,147.34,147.89,46372,572304516
2026-02-26,150.26,150.29,149.0,152.5,145.18,150.31,49966,553933024
2026-02-27,145.32,145.35,143.83,146.04,142.1,145.4,53263,1571801606

IBM.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,304.67,304.81,308.0,312.09,304.24,304.73,12458,364538859
2025-11-04,300.81,300.85,300.0,303.03,296.0,300.85,12701,308971207
2025-11-05,306.54,306.7,301.38,307.2,300.0,306.77,10683,342048393
2025-11-06,312.61,312.62,306.75,315.44,301.09,312.42,13948,359892423
2025-11-07,306.42,306.47,309.68,310.0,302.78,306.38,12883,356202686
...,...,...,...,...,...,...,...,...
2026-02-23,223.34,223.4,253.39,255.02,220.8,223.35,44578,782643955
2026-02-24,229.32,229.42,227.6,236.59,223.63,229.32,38088,669723235
2026-02-25,237.57,237.61,233.3,239.5,231.47,237.54,22033,435944882
2026-02-26,242.01,242.03,239.71,247.38,238.95,242.01,19349,371738811
2026-02-27,240.12,240.15,237.19,240.21,234.66,240.21,15128,511380745

PLTR.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,207.47,207.51,205.045,207.52,201.82,207.18,1247878,16674831338
2025-11-04,190.74,190.75,192.07,195.7,185.56,190.74,2124248,23168876016
2025-11-05,187.88,187.9,189.0,190.32,181.21,187.9,1174659,14168837296
2025-11-06,175.04,175.07,187.99,191.09,174.53,175.05,1227273,14121729615
2025-11-07,177.97,177.99,173.15,178.7,168.91,177.93,1138810,12856649999
...,...,...,...,...,...,...,...,...
2026-02-23,130.59,130.63,132.04,132.04,127.39,130.6,723125,6820453441
2026-02-24,128.75,128.77,129.005,130.24,126.37,128.84,706866,6064619542
2026-02-25,134.18,134.19,130.61,136.09,129.18,134.19,694695,7098490600
2026-02-26,135.94,135.95,133.845,137.51,132.63,135.94,627877,6094734491
2026-02-27,137.19,137.21,134.07,138.1,133.98,137.19,623921,8092979207

NFLX.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,109.938,110.015,113.324,113.35,107.515,110.009,414767,6448388297
2025-11-04,109.276,109.316,109.999,110.45999,108.668,109.296,280402,4232314625
2025-11-05,109.821,109.847,108.5,110.085,107.33701,109.846,259796,3878393486
2025-11-06,109.697,109.739,109.458,110.37,108.513,109.702,258220,3998958612
2025-11-07,110.337,110.348,109.4175,110.822,108.75,110.366,278356,4849943193
...,...,...,...,...,...,...,...,...
2026-02-23,76.04,76.06,77.79,77.83,75.01,76.02,649185,2912849277
2026-02-24,78.03,78.04,75.73,78.12,75.21,78.04,531051,2554940678
2026-02-25,82.71,82.72,79.43,83.117,79.25,82.7,1064539,5688355745
2026-02-26,84.62,84.63,83.2,86.5,82.8,84.59,1182311,7366895815
2026-02-27,96.29,96.31,94.295,96.75,90.58,96.24,2362738,18899267357

TSLA.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,468.32,468.46,455.99,474.07,453.8,468.37,1844855,39577385487
2025-11-04,444.21,444.23,454.46,460.22,443.6,444.26,1924961,39543774192
2025-11-05,462.19,462.27,452.05,466.3299,440.71,462.07,1712752,38889163017
2025-11-06,445.97,446.11,461.96,467.45,435.09,445.91,2216445,49204891758
2025-11-07,429.38,429.39,437.92,439.36,421.88,429.52,2210359,44563047744
...,...,...,...,...,...,...,...,...
2026-02-23,399.82,399.86,407.285,407.7,394.04,399.83,1671357,27800836119
2026-02-24,409.36,409.4,399.5,410.82,397.64,409.38,1296615,23778922621
2026-02-25,417.33,417.39,412.15,420.34,412.15,417.4,1283080,22790551729
2026-02-26,408.46,408.5,414.42,416.81,403.66,408.58,1231898,21892123982
2026-02-27,402.41,402.42,402.94,407.12,398.11,402.51,1268131,22871748855

CRM.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,261.29,261.36,260.0,261.55,255.17,261.34,16457,394322334
2025-11-04,254.34,254.49,258.15,259.26,253.5,254.44,17735,478684412
2025-11-05,252.71,252.72,254.7,256.765,252.02,252.68,14375,356727118
2025-11-06,239.3,239.38,249.75,249.75,234.48,239.27,24113,526805473
2025-11-07,239.87,239.9,236.15,240.96,236.0,239.88,15489,355365217
...,...,...,...,...,...,...,...,...
2026-02-23,178.2,178.21,181.27,181.58,174.62,178.16,33725,570762648
2026-02-24,185.44,185.51,177.0,188.64,176.28,185.42,28545,574576070
2026-02-25,191.9,191.96,183.0,192.59,182.96,191.75,27663,614577515
2026-02-26,199.47,199.49,195.0,201.0,191.37,199.47,42038,852407276
2026-02-27,194.79,194.8,190.54,195.905,190.0,194.79,24897,738859653

AMD.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,259.64,259.65,259.33,260.91,253.89,259.65,511152,9367739445
2025-11-04,250.09,250.2,250.35,257.38,247.39,250.05,856151,14216615129
2025-11-05,255.63,255.99,243.24,259.65,242.805,256.33,833731,16999841855
2025-11-06,237.6,237.62,253.465,253.51,235.74,237.7,865210,15915099293
2025-11-07,233.55,233.57,230.94,235.87,224.6401,233.54,748603,11998754359
...,...,...,...,...,...,...,...,...
2026-02-23,196.57,196.6,198.09,199.38,194.15,196.6,410589,5534731902
2026-02-24,213.74,213.82,211.63,216.71,206.5,213.84,1005328,17328300216
2026-02-25,210.85,210.93,214.82,216.7,210.33,210.86,609716,9457531866
2026-02-26,203.66,203.7,208.8,209.79,201.46,203.68,547642,7143981183
2026-02-27,200.17,200.21,200.105,201.89,197.74,200.21,469445,6256546968

INTC.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,39.49,39.5,40.25,40.45,39.05,39.5,325372,2429773978
2025-11-04,37.05,37.06,38.14,38.25,36.63,37.03,472247,3848419409
2025-11-05,38.32,38.33,37.415,38.6898,37.11,38.38,336954,2839612674
2025-11-06,37.24,37.25,38.335,39.8446,36.8,37.24,349561,2908900605
2025-11-07,38.15,38.16,37.26,38.27,36.97,38.13,463771,3589332104
...,...,...,...,...,...,...,...,...
2026-02-23,43.64,43.65,44.09,44.55,43.18,43.63,340652,2500844469
2026-02-24,46.12,46.13,44.095,46.6,43.54,46.12,532954,4500152201
2026-02-25,46.9,46.91,46.09,46.97,45.08,46.88,441041,3507326621
2026-02-26,45.47,45.48,46.77,46.95,44.39,45.46,434086,3244054197
2026-02-27,45.58,45.59,44.46,46.56,44.4,45.61,374043,3660534026

ARM.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,168.58,168.68,171.3,173.54,168.36,168.68,44343,380285539
2025-11-04,160.53,160.74,162.0,166.14,160.4,160.73,71309,639091012
2025-11-05,160.0,160.1,158.74,164.33,156.33,160.19,109326,1120374520
2025-11-06,158.23,158.41,167.0,167.4799,155.18,158.25,113847,1137077687
2025-11-07,152.26,152.5,154.74,155.23,146.29,152.38,112175,870359465
...,...,...,...,...,...,...,...,...
2026-02-23,123.77,123.85,123.705,126.71,121.91,123.78,55593,419768486
2026-02-24,128.0,128.1,124.6,131.39,124.0,128.14,66413,550050598
2026-02-25,131.63,131.77,128.35,133.28,128.35,131.74,81971,569078631
2026-02-26,129.27,129.32,131.94,134.25,126.66,129.26,67103,533780491
2026-02-27,127.41,127.58,126.145,128.89,126.01,127.45,49585,395758118

TXN.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,161.44,161.46,162.34,163.45,160.07,161.46,83321,840515975
2025-11-04,159.36,159.37,161.18,162.305,158.13,159.36,119995,1828895183
2025-11-05,163.5,163.52,159.39,165.62,159.39,163.57,112901,1594958031
2025-11-06,161.42,161.45,162.75,163.81,161.09,161.38,97675,947987414
2025-11-07,160.55,160.56,160.38,160.6,156.89,160.55,121253,1409228937
...,...,...,...,...,...,...,...,...
2026-02-23,219.86,219.93,218.9,222.79,218.9,219.86,92608,1736519594
2026-02-24,213.29,213.41,220.72,224.17,209.59,213.35,131976,2036366788
2026-02-25,213.79,213.9,214.4,215.9,210.23,213.9,90602,1495635484
2026-02-26,212.61,212.65,214.45,216.09,210.15,212.63,93264,1282836943
2026-02-27,211.99,212.08,211.23,212.63,208.25,212.11,87426,1745805752

CSCO.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,74.47,74.48,74.61,74.838,73.6243,74.45,189178,1615723634
2025-11-04,72.33,72.34,73.9,73.99,71.98,72.32,186123,1624975421
2025-11-05,72.1,72.11,72.22,72.58,71.34,72.1,150130,1161521140
2025-11-06,71.06,71.07,71.71,72.23,70.6903,71.04,149179,1173867572
2025-11-07,71.07,71.09,71.385,71.585,70.54,71.07,151927,1201583213
...,...,...,...,...,...,...,...,...
2026-02-23,77.75,77.76,78.85,79.48,76.94,77.74,216683,1905980687
2026-02-24,78.14,78.15,77.74,78.71,77.47,78.14,178933,1524751970
2026-02-25,79.11,79.12,78.45,79.42,78.26,79.12,173236,1792931462
2026-02-26,78.13,78.15,78.94,79.3396,77.72,78.1,171230,1534430142
2026-02-27,79.48,79.5,77.65,79.53,77.07,79.46,181541,2171517735

WMT.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,101.6,101.61,100.815,101.8,100.4,101.59,235916,1499079430
2025-11-04,102.3,102.31,102.13,102.62,101.46,102.27,204859,1290939801
2025-11-05,101.47,101.48,101.74,102.675,100.85,101.47,205580,1358604675
2025-11-06,101.67,101.71,101.34,101.93,100.03,101.68,201238,1506405436
2025-11-07,102.61,102.63,102.13,102.97,101.73,102.59,231211,1768604440
...,...,...,...,...,...,...,...,...
2026-02-23,125.82,125.85,123.52,126.8,122.96,125.81,296745,3222903036
2026-02-24,126.75,126.76,125.9,128.04,124.91,126.75,220165,2557194058
2026-02-25,125.77,125.79,126.605,127.4,125.42,125.75,189245,2187367417
2026-02-26,124.4,124.42,125.98,127.33,123.94,124.42,209179,2325230022
2026-02-27,127.91,127.92,125.515,128.6,125.145,127.95,237331,3723505650

LLY.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,896.86,897.05,866.5,901.21,862.62,896.53,19279,882161465
2025-11-04,907.02,907.54,889.56,915.125,884.6,906.86,21505,907470232
2025-11-05,925.84,926.5,910.0,955.435,907.86,925.81,35090,1349349720
2025-11-06,937.83,937.94,928.0,949.9,916.37,937.44,20502,1109551191
2025-11-07,924.04,924.47,931.17,932.0,901.0,924.37,17288,782735038
...,...,...,...,...,...,...,...,...
2026-02-23,1058.11,1058.51,1047.16,1064.35,1035.0,1058.56,12128,887968678
2026-02-24,1042.3,1042.94,1042.33,1058.7,1024.08,1042.15,9653,760674730
2026-02-25,1029.53,1029.54,1036.58,1053.52,1027.08,1028.83,8114,558455761
2026-02-26,1021.95,1021.96,1024.08,1025.32,1007.49,1022.02,10137,630636701
2026-02-27,1051.71,1052.1,1017.43,1053.0,1017.43,1051.99,11447,1649455123

JPM.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,309.66,309.67,311.73,312.25,306.24,309.35,27635,757543848
2025-11-04,309.23,309.27,306.71,312.2,305.15,309.25,20668,634510594
2025-11-05,311.72,311.77,309.61,313.08,305.77,311.68,22097,653277963
2025-11-06,313.68,313.75,311.41,314.83,310.26,313.42,30890,811659262
2025-11-07,314.22,314.26,311.89,314.42,307.74,314.21,27117,681709743
...,...,...,...,...,...,...,...,...
2026-02-23,297.77,297.87,308.14,311.0,295.1,297.67,43704,962333755
2026-02-24,297.29,297.39,297.63,299.74,291.38,297.3,31947,861951320
2026-02-25,303.33,303.36,298.67,303.65,297.14,303.3,27023,681151782
2026-02-26,306.12,306.17,304.58,309.0,303.68,306.13,23440,605311876
2026-02-27,299.92,300.12,301.05,302.95,294.48,300.3,38588,2307962866

XOM.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,113.83,113.85,114.26,114.98,113.65,113.76,16254,317433367
2025-11-04,114.18,114.2,113.35,114.345,112.56,114.14,14471,404107743
2025-11-05,113.71,113.73,114.36,115.16,113.675,113.68,11735,362020138
2025-11-06,114.5,114.52,113.86,114.93,113.74,114.5,19612,472450330
2025-11-07,117.22,117.24,115.24,117.5,114.905,117.22,20020,447199444
...,...,...,...,...,...,...,...,...
2026-02-23,150.81,150.84,148.26,151.27,148.22,150.76,24731,625993063
2026-02-24,149.29,149.33,150.3,150.6,148.03,149.26,19880,513451887
2026-02-25,149.06,149.07,149.81,150.15,147.33,149.06,18790,495290878
2026-02-26,148.56,148.58,147.6,150.94,146.8,148.54,24678,539079360
2026-02-27,152.6,152.61,151.22,153.65,149.26,152.5,27266,1909376059

V.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,336.87,336.98,341.0,341.1,334.86,336.9,16062,645632804
2025-11-04,340.21,340.22,336.48,340.31,334.25,340.3,17709,483269512
2025-11-05,340.07,340.15,340.13,342.05,336.36,340.04,10517,399360591
2025-11-06,337.02,337.07,336.94,337.87,333.77,336.96,15521,1274805757
2025-11-07,336.09,336.1,337.0,338.27,334.9,336.02,14433,449863391
...,...,...,...,...,...,...,...,...
2026-02-23,306.52,306.57,317.09,320.51,304.71,306.52,35848,824759965
2026-02-24,307.22,307.26,305.38,309.26,303.13,307.22,25387,596516732
2026-02-25,313.0,313.04,309.39,313.94,309.29,312.99,17856,511830923
2026-02-26,316.69,316.86,314.48,319.34,313.94,316.7,16477,960787511
2026-02-27,319.96,319.97,314.3,320.23,312.0,320.14,22748,1952293249

JNJ.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,186.25,186.26,189.0,189.0,185.535,186.26,14564,361608828
2025-11-04,186.86,186.87,186.96,187.82,185.64,186.86,11307,384848232
2025-11-05,186.01,186.02,186.51,187.82,185.42,186.0,11690,354188917
2025-11-06,187.01,187.04,186.76,187.5,185.42,186.97,12244,419298564
2025-11-07,186.52,186.53,187.74,188.24,185.71,186.57,12521,441446670
...,...,...,...,...,...,...,...,...
2026-02-23,245.81,245.84,243.63,246.76,243.27,245.84,15153,528982059
2026-02-24,246.28,246.29,245.01,247.21,244.71,246.28,10310,409331527
2026-02-25,245.16,245.2,244.86,247.2,243.72,245.17,10235,575475000
2026-02-26,243.46,243.48,245.11,245.11,242.05,243.47,12391,406625078
2026-02-27,248.45,248.48,244.03,248.93,243.41,248.43,14547,1966745944

MU.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,234.66,234.7,233.875,237.62,231.8,234.7,329304,4974038703
2025-11-04,218.01,218.08,222.14,228.6726,217.4,218.03,393028,5264074476
2025-11-05,237.38,237.49,225.665,239.88,224.725,237.5,417017,6717367125
2025-11-06,238.36,238.42,237.84,246.41,234.88,238.33,440457,7670211501
2025-11-07,237.88,237.93,234.03,242.55,226.4001,237.92,463136,7157593086
...,...,...,...,...,...,...,...,...
2026-02-23,421.19,421.24,422.31,431.695,415.3001,420.97,440610,10712621707
2026-02-24,417.98,418.2,429.22,436.27,411.28,418.01,576571,14145085957
2026-02-25,428.81,428.87,426.5,436.8899,423.0,429.0,477670,11709759184
2026-02-26,415.51,415.73,424.84,434.0,401.96,415.56,622380,14711633341
2026-02-27,412.15,412.28,401.81,417.96,401.1818,412.37,435584,11774531639

MA.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,544.11,544.33,550.0,550.74,540.38,544.07,12062,428716953
2025-11-04,552.82,552.91,544.83,554.0,542.77,552.75,10378,343216312
2025-11-05,553.25,553.45,553.0,555.98,549.54,553.31,11728,383867568
2025-11-06,553.44,553.71,550.31,554.98,548.0,553.28,14139,599987553
2025-11-07,551.5,552.04,553.8,558.36,550.74,551.97,13364,465158289
...,...,...,...,...,...,...,...,...
2026-02-23,495.97,496.44,520.47,522.6,490.0,496.03,24090,657203241
2026-02-24,498.01,498.29,495.49,499.24,491.27,498.0,22213,635894988
2026-02-25,509.42,509.51,502.82,510.45,502.55,509.39,14307,462593527
2026-02-26,514.53,514.54,510.95,519.79,509.185,514.77,21633,693456409
2026-02-27,517.0,517.13,509.47,518.72,507.01,517.21,12588,895897348

COST.O,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,928.16,928.29,912.4,929.1899,908.38,928.04,115016,2955724842
2025-11-04,940.69,940.92,933.21,941.17,928.965,940.74,118632,2393156755
2025-11-05,934.97,935.56,940.0,945.28,927.44,935.03,104555,2787781262
2025-11-06,923.64,923.84,924.36,925.0,908.3,923.58,135257,2984022191
2025-11-07,922.52,922.74,929.53,937.0,920.79,922.74,107693,2392427938
...,...,...,...,...,...,...,...,...
2026-02-23,985.94,986.25,981.8,991.305,978.06,986.02,78659,1466465045
2026-02-24,998.0,998.43,986.38,998.88,985.04,998.43,67679,1664358849
2026-02-25,994.64,994.76,997.675,1002.5,991.44,994.76,70744,1546236501
2026-02-26,986.62,986.68,996.915,1005.5199,983.53,986.74,81791,1785119420
2026-02-27,1011.18,1011.19,990.53,1014.19,989.58,1010.79,99021,3960013179

CVX.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,154.13,154.14,157.43,157.71,153.575,154.04,18762,343046267
2025-11-04,153.39,153.4,153.0,153.74,152.2,153.39,12552,276717127
2025-11-05,152.66,152.69,153.7,154.39,152.66,152.66,13649,304219400
2025-11-06,152.99,153.02,153.13,154.76,152.78,152.94,13669,297511449
2025-11-07,155.07,155.11,153.84,156.14,153.8,155.02,16128,373659604
...,...,...,...,...,...,...,...,...
2026-02-23,184.96,185.0,184.71,186.6,184.11,184.91,14947,311735882
2026-02-24,185.35,185.36,185.0,185.92,183.86,185.34,12222,398207727
2026-02-25,184.21,184.22,185.9,185.97,182.52,184.22,12018,275577549
2026-02-26,184.13,184.14,182.17,186.26,182.16,184.16,13312,267118221
2026-02-27,186.75,186.76,186.0,187.54,183.79,186.76,17928,802387509

BAC.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,53.57,53.58,53.28,53.635,52.71,53.56,45885,501856018
2025-11-04,53.56,53.57,53.02,53.995,52.72,53.54,44302,693332605
2025-11-05,52.44,52.45,52.96,53.01,51.74,52.45,45208,792708964
2025-11-06,53.32,53.33,53.4,53.75,52.775,53.29,65332,883201476
2025-11-07,53.22,53.23,53.01,53.58,52.71,53.2,54299,659976474
...,...,...,...,...,...,...,...,...
2026-02-23,51.08,51.09,52.86,53.26,50.89,51.07,51379,647428392
2026-02-24,50.4,50.41,50.6,50.875,49.475,50.41,54571,846964785
2026-02-25,51.7,51.71,50.6,51.76,50.43,51.69,37255,695910710
2026-02-26,52.29,52.3,51.88,52.67,51.75,52.3,42276,1451883232
2026-02-27,49.8,49.81,51.34,51.41,49.32,49.83,61761,1506147994

CAT.N,BID,ASK,OPEN_PRC,HIGH_1,LOW_1,TRDPRC_1,NUM_MOVES,TRNOVR_UNS
Date,,,,,,,,
2025-11-03,570.48,570.71,575.93,575.99,565.6,570.59,8981,327627161
2025-11-04,547.44,547.45,565.0,566.19,545.47,547.58,11995,380089113
2025-11-05,569.15,569.16,551.94,574.0,550.5,569.15,10508,339627630
2025-11-06,569.76,570.02,573.2,583.56,564.49,569.78,7961,260155756
2025-11-07,563.05,563.27,563.55,565.5,551.39,563.1,10142,339320010
...,...,...,...,...,...,...,...,...
2026-02-23,756.5,757.09,757.69,767.98,753.03,756.47,7606,523074157
2026-02-24,768.26,768.57,755.0,773.625,752.01,768.23,9445,503656726
2026-02-25,766.43,766.44,771.51,777.37,756.74,766.61,9791,472057874
2026-02-26,752.73,752.74,763.83,767.09,728.47,752.93,13544,592145453
2026-02-27,742.84,743.14,745.22,751.49,731.29,742.83,8767,786363021

Closing the session.

In [ ]:
# Close the session to release resources; in a long-running application, consider keeping the session open and reusing it for subsequent API calls instead.
ld_session.close()
ld.close_session()